### PR TITLE
Add a cmake option to not install zmq block

### PR DESCRIPTION
**Pull request by reiinakano**
Hello, thanks for your great OOT. For our purposes, we don't need the ZMQ block and would rather not have a ZMQ dependency in our production build. So we added a configuration option `ENABLE_SATTOOLS_ZEROMQ` that will not install the ZMQ block if set to OFF i.e. `cmake -DENABLE_SATTOOLS_ZEROMQ=OFF ../`. By default, it will be ON so there should be no difference in behavior for people who don't care. 

Let us know if this is something you think is worth merging into the main repo.

cc @kenichi-fukushima @anuraaga

### CODE REVIEW

**Comment by anuraaga** [comment]
For a bit more context, this option is inspired by `ENABLE_GR_ZEROMQ` in the main codebase

https://github.com/gnuradio/gnuradio/blob/master/gr-zeromq/CMakeLists.txt#L48

**Comment by mndza** [comment]
Looks good :+1:. I am glad you find this useful. Thank you!

**Comment by mndza** [comment]
Updated the README.md file to reflect the new option.

**Comment by mndza** [comment]
I should have asked for a rebase first, so while fixing my screwed up history my master branch is now different than yours. Sorry for the inconvenience.

**Comment by reiinakano** [comment]
No problem! Actually GitHub has an option called "squash and merge" that
does the rebase automatically upon merge :)

**Pull request merged**
